version: "3.9"

services:
  postgres:
    image: "postgres:14.4"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test3
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres
      - TZ=Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data
      

  redis:
    image: "redis:7.0.4-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: